name: "Build Example rollow nice_nano_v2"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["rollow_left","rollow_right"]'
